name: izinto
description: An ondemand delivery platform


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  get: ^4.6.1
  dots_indicator: ^2.1.0
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^4.0.2
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  material_design_icons_flutter: ^6.0.7096
  progress_indicators: ^1.0.0
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.0
  flutter_native_splash: ^2.2.16
  simple_circular_progress_bar: ^1.0.2
  pinput: ^2.2.16
  provider: ^6.0.4
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  uuid: ^3.0.7
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: ^0.10.0


flutter_icons:
  image_path: "assets/image/asset.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/image/logo9.png"
  adaptive_icon_background: "#ffffff"


  flutter_lints: ^1.0.0
flutter_launcher_name:
  name: "Izinto"



flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/DB/specialties/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
    - family: BIZUDGothic
      fonts:
        - asset: assets/font/BIZUDGothic-Regular.ttf
          weight: 400
    - family: Hind
      fonts: